"""Add PH tables

Revision ID: 0a7697dcc5a6
Revises: c43cc47f91dc
Create Date: 2026-01-16 14:11:37.086924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7697dcc5a6'
down_revision: Union[str, Sequence[str], None] = 'c43cc47f91dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_sistema_clave'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.alter_column('ph_configuracion', 'tipo_negocio',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PH_RESIDENCIAL'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ph_configuracion', 'tipo_negocio',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PH_RESIDENCIAL'::character varying"))
    op.create_table('configuracion_sistema',
    sa.Column('clave', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('configuracion_sistema_pkey'))
    )
    op.create_index(op.f('ix_configuracion_sistema_clave'), 'configuracion_sistema', ['clave'], unique=False)
    # ### end Alembic commands ###
