"""Alinear columna clase en PlanCuenta y cambiar a Integer

Revision ID: 0d837c1fe883
Revises: 9b51c35f89f3
Create Date: 2025-11-04 23:11:15.633041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d837c1fe883'
down_revision: Union[str, Sequence[str], None] = '9b51c35f89f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_cuentas', sa.Column('clase', sa.Integer(), nullable=True))
    op.drop_column('plan_cuentas', 'clase_cuenta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan_cuentas', sa.Column('clase_cuenta', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('plan_cuentas', 'clase')
    # ### end Alembic commands ###
