"""Restore payroll tables

Revision ID: 10a7f6e76b82
Revises: 6807db7c0dee
Create Date: 2025-12-09 19:59:47.209997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a7f6e76b82'
down_revision: Union[str, Sequence[str], None] = '6807db7c0dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nomina_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('periodo_pago', postgresql.ENUM('MENSUAL', 'QUINCENAL', name='periodopago', create_type=False), nullable=True),
    sa.Column('quincena', sa.Integer(), nullable=True),
    sa.Column('fecha_liquidacion', sa.Date(), nullable=True),
    sa.Column('fecha_inicio_periodo', sa.Date(), nullable=False),
    sa.Column('fecha_fin_periodo', sa.Date(), nullable=False),
    sa.Column('total_devengado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deducciones', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_neto', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('estado', postgresql.ENUM('BORRADOR', 'APROBADA', 'PAGADA', 'ANULADA', name='estadonomina', create_type=False), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomina_documentos_id'), 'nomina_documentos', ['id'], unique=False)
    op.create_table('nomina_empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_documento', sa.String(length=5), nullable=True),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('tipo_contrato', postgresql.ENUM('INDEFINIDO', 'FIJO', 'OBRA_LABOR', 'APRENDIZ', 'PRESTACION_SERVICIOS', name='tipocontrato', create_type=False), nullable=True),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('salario_base', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('auxilio_transporte', sa.Boolean(), nullable=True),
    sa.Column('riesgo_arl', sa.Integer(), nullable=True),
    sa.Column('banco', sa.String(length=50), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('estado', postgresql.ENUM('ACTIVO', 'INACTIVO', 'LICENCIA', name='estadoempleado', create_type=False), nullable=True),
    sa.Column('tercero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomina_empleados_id'), 'nomina_empleados', ['id'], unique=False)
    op.create_index(op.f('ix_nomina_empleados_numero_documento'), 'nomina_empleados', ['numero_documento'], unique=False)
    op.create_table('nomina_configuracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_sueldo_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_auxilio_transporte_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_horas_extras_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_comisiones_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_salarios_por_pagar_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_aporte_salud_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_aporte_pension_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_fondo_solidaridad_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_retencion_fuente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_aporte_pension_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_aporte_salud_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_auxilio_transporte_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_comisiones_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_fondo_solidaridad_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_horas_extras_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_retencion_fuente_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_salarios_por_pagar_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_sueldo_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_index(op.f('ix_nomina_configuracion_id'), 'nomina_configuracion', ['id'], unique=False)
    op.create_table('nomina_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomina_id', sa.Integer(), nullable=True),
    sa.Column('empleado_id', sa.Integer(), nullable=True),
    sa.Column('dias_trabajados', sa.Integer(), nullable=True),
    sa.Column('dias_incapacidad', sa.Integer(), nullable=True),
    sa.Column('dias_licencia', sa.Integer(), nullable=True),
    sa.Column('sueldo_basico_periodo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('auxilio_transporte_periodo', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('horas_extras_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('recargos_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('comisiones', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('otros_devengados', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_devengado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('salud_empleado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pension_empleado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fondo_solidaridad', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('retencion_fuente', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('prestamos', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('otras_deducciones', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_deducciones', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('neto_pagar', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['nomina_empleados.id'], ),
    sa.ForeignKeyConstraint(['nomina_id'], ['nomina_documentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nomina_detalles_id'), 'nomina_detalles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nomina_detalles_id'), table_name='nomina_detalles')
    op.drop_table('nomina_detalles')
    op.drop_index(op.f('ix_nomina_configuracion_id'), table_name='nomina_configuracion')
    op.drop_table('nomina_configuracion')
    op.drop_index(op.f('ix_nomina_empleados_numero_documento'), table_name='nomina_empleados')
    op.drop_index(op.f('ix_nomina_empleados_id'), table_name='nomina_empleados')
    op.drop_table('nomina_empleados')
    op.drop_index(op.f('ix_nomina_documentos_id'), table_name='nomina_documentos')
    op.drop_table('nomina_documentos')
    # ### end Alembic commands ###
