"""add_licencia_fields_to_empresas

Revision ID: 1309082a4c2b
Revises: 9e67bde226aa
Create Date: 2026-05-04 12:44:35.104767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1309082a4c2b'
down_revision: Union[str, Sequence[str], None] = '9e67bde226aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_tutor_messages')
    op.drop_index(op.f('ix_configuracion_sistema_clave'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.drop_index(op.f('ix_soporte_tickets_id'), table_name='soporte_tickets')
    op.drop_table('soporte_tickets')
    op.add_column('empresas', sa.Column('licencia_key', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('licencia_version', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('licencia_cliente', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('licencia_activada_en', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'licencia_activada_en')
    op.drop_column('empresas', 'licencia_cliente')
    op.drop_column('empresas', 'licencia_version')
    op.drop_column('empresas', 'licencia_key')
    op.create_table('soporte_tickets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tercero_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asunto', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('respuesta_soporte', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('soporte_tickets_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['tercero_id'], ['terceros.id'], name=op.f('soporte_tickets_tercero_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('soporte_tickets_pkey'))
    )
    op.create_index(op.f('ix_soporte_tickets_id'), 'soporte_tickets', ['id'], unique=False)
    op.create_table('configuracion_sistema',
    sa.Column('clave', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('configuracion_sistema_pkey'))
    )
    op.create_index(op.f('ix_configuracion_sistema_clave'), 'configuracion_sistema', ['clave'], unique=False)
    op.create_table('ai_tutor_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('ai_tutor_messages_empresa_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('ai_tutor_messages_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_tutor_messages_pkey'))
    )
    # ### end Alembic commands ###
