"""Add email configuration module

Revision ID: 1be73c91d2bd
Revises: f7addb49d1cc
Create Date: 2025-12-23 12:37:35.454701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be73c91d2bd'
down_revision: Union[str, Sequence[str], None] = 'f7addb49d1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plan_cuentas_is_bank_reconciliation_account'), 'plan_cuentas', ['is_bank_reconciliation_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_cuentas_is_bank_reconciliation_account'), table_name='plan_cuentas')
    # ### end Alembic commands ###
