"""create_advanced_budget_tables

Revision ID: 28eabec8985c
Revises: e51ec728bb0b
Create Date: 2026-01-27 13:34:24.429369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28eabec8985c'
down_revision: Union[str, Sequence[str], None] = 'e51ec728bb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_reglas_empresa_id'), table_name='ocr_reglas')
    op.drop_index(op.f('ix_ocr_reglas_id'), table_name='ocr_reglas')
    op.drop_table('ocr_reglas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_reglas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('condicion_texto', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Texto a buscar'),
    sa.Column('condicion_operador', postgresql.ENUM('CONTAINS', 'EQUALS', 'STARTS_WITH', 'ENDS_WITH', name='ocrreglaoperador'), autoincrement=False, nullable=False),
    sa.Column('tipo_documento_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beneficiario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cuenta_debito_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('centro_costo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cuenta_credito_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['terceros.id'], name=op.f('ocr_reglas_beneficiario_id_fkey')),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], name=op.f('ocr_reglas_centro_costo_id_fkey')),
    sa.ForeignKeyConstraint(['cuenta_credito_id'], ['plan_cuentas.id'], name=op.f('ocr_reglas_cuenta_credito_id_fkey')),
    sa.ForeignKeyConstraint(['cuenta_debito_id'], ['plan_cuentas.id'], name=op.f('ocr_reglas_cuenta_debito_id_fkey')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('ocr_reglas_empresa_id_fkey')),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], name=op.f('ocr_reglas_tipo_documento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ocr_reglas_pkey'))
    )
    op.create_index(op.f('ix_ocr_reglas_id'), 'ocr_reglas', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_reglas_empresa_id'), 'ocr_reglas', ['empresa_id'], unique=False)
    # ### end Alembic commands ###
