"""Add PHConcepto model

Revision ID: 3db1ab3fe27b
Revises: 59f388cd29e4
Create Date: 2025-12-16 19:15:06.875572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db1ab3fe27b'
down_revision: Union[str, Sequence[str], None] = '59f388cd29e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'prefijo_cxc',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('empresas', 'prefijo_cxp',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'2'::character varying"))
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.drop_constraint(op.f('formatos_documento_impresion_empresa_nombre_key'), 'formatos_documento_impresion', type_='unique')
    op.create_unique_constraint(None, 'formatos_documento_impresion', ['nombre'])
    op.alter_column('stock_bodegas', 'stock_comprometido',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table('ph_conceptos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cuenta_ingreso_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_cxc_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_interes_id', sa.Integer(), nullable=True),
    sa.Column('usa_coeficiente', sa.Boolean(), nullable=True),
    sa.Column('es_fijo', sa.Boolean(), nullable=True),
    sa.Column('valor_defecto', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_cxc_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_ingreso_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_interes_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ph_conceptos_id'), 'ph_conceptos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_bodegas', 'stock_comprometido',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'formatos_documento_impresion', type_='unique')
    op.create_unique_constraint(op.f('formatos_documento_impresion_empresa_nombre_key'), 'formatos_documento_impresion', ['empresa_id', 'nombre'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.alter_column('empresas', 'prefijo_cxp',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'2'::character varying"))
    op.alter_column('empresas', 'prefijo_cxc',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_ph_conceptos_id'), table_name='ph_conceptos')
    op.drop_table('ph_conceptos')
    # ### end Alembic commands ###
