"""add_tercero_id_to_movimiento_contable

Revision ID: 4b6ed1a29389
Revises: 72136b08f832
Create Date: 2026-01-03 20:21:51.826857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6ed1a29389'
down_revision: Union[str, Sequence[str], None] = '72136b08f832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos_contables', sa.Column('tercero_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimientos_contables', 'terceros', ['tercero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimientos_contables', type_='foreignkey')
    op.drop_column('movimientos_contables', 'tercero_id')
    # ### end Alembic commands ###
