"""Create fixed assets module tables (categorias, activos, novedades)

Revision ID: 51b56baab5c4
Revises: b1d0da911547
Create Date: 2025-12-06 22:32:56.182032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51b56baab5c4'
down_revision: Union[str, Sequence[str], None] = 'b1d0da911547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cotizaciones_detalles_cotizacion_id_fkey'), 'cotizaciones_detalles', type_='foreignkey')
    op.create_foreign_key(None, 'cotizaciones_detalles', 'cotizaciones', ['cotizacion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cotizaciones_detalles', type_='foreignkey')
    op.create_foreign_key(op.f('cotizaciones_detalles_cotizacion_id_fkey'), 'cotizaciones_detalles', 'cotizaciones', ['cotizacion_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
