"""link_config_to_tipo_nomina

Revision ID: 51c27b29d356
Revises: b481fb0e2488
Create Date: 2025-12-09 23:15:07.405256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c27b29d356'
down_revision: Union[str, Sequence[str], None] = 'b481fb0e2488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nomina_configuracion', sa.Column('tipo_nomina_id', sa.Integer(), nullable=True))
    op.drop_constraint('nomina_configuracion_empresa_id_key', 'nomina_configuracion', type_='unique') # Explicitly naming if possible, but auto-gen uses op.f sometimes. Using the name seen in downgrade is safer if known.
    # The auto-gen used op.f('nomina_configuracion_empresa_id_key') which is good.
    # Let's stick to what was there for nomina_configuracion but remove the rest.
    
    op.create_unique_constraint('uq_config_empresa_tipo', 'nomina_configuracion', ['empresa_id', 'tipo_nomina_id'])
    op.create_foreign_key(None, 'nomina_configuracion', 'nomina_tipos', ['tipo_nomina_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nomina_configuracion', type_='foreignkey')
    op.drop_constraint('uq_config_empresa_tipo', 'nomina_configuracion', type_='unique')
    op.create_unique_constraint('nomina_configuracion_empresa_id_key', 'nomina_configuracion', ['empresa_id'])
    op.drop_column('nomina_configuracion', 'tipo_nomina_id')
    # ### end Alembic commands ###
