"""Crear tablas Indicator y RuleDiagnostic para motor M-RAC

Revision ID: 56374b41b01a
Revises: 7b2dec53864f
Create Date: 2025-11-06 13:50:47.877374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56374b41b01a'
down_revision: Union[str, Sequence[str], None] = '7b2dec53864f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
