"""Add unidad_ph_id to Documento

Revision ID: 59f388cd29e4
Revises: 793269a43c31
Create Date: 2025-12-16 18:53:31.526113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f388cd29e4'
down_revision: Union[str, Sequence[str], None] = '793269a43c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('unidad_ph_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'documentos', 'ph_unidades', ['unidad_ph_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentos', type_='foreignkey')
    op.drop_column('documentos', 'unidad_ph_id')
    # ### end Alembic commands ###
