"""add_ph_tipo_doc_recibo

Revision ID: 6807db7c0dee
Revises: f596acd9b6b3
Create Date: 2025-12-08 11:26:36.208256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6807db7c0dee'
down_revision: Union[str, Sequence[str], None] = 'f596acd9b6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ph_configuracion', sa.Column('tipo_documento_recibo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ph_configuracion', 'tipos_documento', ['tipo_documento_recibo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ph_configuracion', type_='foreignkey')
    op.drop_column('ph_configuracion', 'tipo_documento_recibo_id')
    # ### end Alembic commands ###
