"""create usuarios_busquedas_guardadas table

Revision ID: 72136b08f832
Revises: 1be73c91d2bd
Create Date: 2025-12-24 12:10:41.547430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72136b08f832'
down_revision: Union[str, Sequence[str], None] = '1be73c91d2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_busquedas_guardadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('comando', sa.Text(), nullable=False),
    sa.Column('parametros', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_busquedas_guardadas_id'), 'usuarios_busquedas_guardadas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_busquedas_guardadas_id'), table_name='usuarios_busquedas_guardadas')
    op.drop_table('usuarios_busquedas_guardadas')
    # ### end Alembic commands ###
