"""Aumentar el límite de orden de UsuarioFavorito a 12 y corregir la restricción de unicidad.

Revision ID: 7b2dec53864f
Revises: 0d837c1fe883
Create Date: 2025-11-05 00:16:23.964846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b2dec53864f'
down_revision: Union[str, Sequence[str], None] = '0d837c1fe883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
