"""add_billing_fields_to_recargas

Revision ID: 81c0f8f9959f
Revises: f1cd9d19816d
Create Date: 2026-01-07 21:53:47.586793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c0f8f9959f'
down_revision: Union[str, Sequence[str], None] = 'f1cd9d19816d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recarga_adicional', sa.Column('valor_total', sa.Integer(), nullable=False))
    op.add_column('recarga_adicional', sa.Column('facturado', sa.Boolean(), nullable=True))
    op.add_column('recarga_adicional', sa.Column('fecha_facturacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recarga_adicional', 'fecha_facturacion')
    op.drop_column('recarga_adicional', 'facturado')
    op.drop_column('recarga_adicional', 'valor_total')
    # ### end Alembic commands ###
