"""Expandir modelos inventario con unidad, topes, caracteristicas, impuesto_grupo y listas_precio

Revision ID: 81e008735b1f
Revises: a9875538e338
Create Date: 2025-10-18 13:57:23.988249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e008735b1f'
down_revision: Union[str, Sequence[str], None] = 'a9875538e338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_inventario', sa.Column('impuesto_predeterminado_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos_inventario', 'tasas_impuesto', ['impuesto_predeterminado_id'], ['id'])
    op.add_column('productos', sa.Column('unidad_medida', sa.String(length=50), nullable=True))
    op.add_column('productos', sa.Column('stock_minimo', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('stock_maximo', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('caracteristicas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'caracteristicas')
    op.drop_column('productos', 'stock_maximo')
    op.drop_column('productos', 'stock_minimo')
    op.drop_column('productos', 'unidad_medida')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'impuesto_predeterminado_id')
    # ### end Alembic commands ###
