"""add_ph_coeficiente_historial

Revision ID: 8b33f1f33de8
Revises: ba9541e366f4
Create Date: 2025-12-07 23:30:56.984271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b33f1f33de8'
down_revision: Union[str, Sequence[str], None] = 'ba9541e366f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
