"""add_manual_limit_flag_to_plan_mensual

Revision ID: 96dcf40423b2
Revises: f745edeea36a
Create Date: 2026-01-09 21:05:38.793148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96dcf40423b2'
down_revision: Union[str, Sequence[str], None] = 'f745edeea36a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_plan_mensual', sa.Column('es_manual', sa.Boolean(), nullable=True, server_default='false'))

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('control_plan_mensual', 'es_manual')
