"""Crear tabla usuarios_favoritos para accesos rapidos

Revision ID: 9b51c35f89f3
Revises: 09abbc450ae9
Create Date: 2025-11-04 21:09:02.565202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b51c35f89f3'
down_revision: Union[str, Sequence[str], None] = '09abbc450ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
