"""Add production consumption and entry doc types

Revision ID: 9e25fe660694
Revises: ec7e749d3287
Create Date: 2025-12-10 14:56:11.738283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e25fe660694'
down_revision: Union[str, Sequence[str], None] = 'ec7e749d3287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produccion_configuracion', sa.Column('tipo_documento_consumo_id', sa.Integer(), nullable=True))
    op.add_column('produccion_configuracion', sa.Column('tipo_documento_entrada_pt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produccion_configuracion', 'tipos_documento', ['tipo_documento_entrada_pt_id'], ['id'])
    op.create_foreign_key(None, 'produccion_configuracion', 'tipos_documento', ['tipo_documento_consumo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produccion_configuracion', type_='foreignkey')
    op.drop_constraint(None, 'produccion_configuracion', type_='foreignkey')
    op.drop_column('produccion_configuracion', 'tipo_documento_entrada_pt_id')
    op.drop_column('produccion_configuracion', 'tipo_documento_consumo_id')
    # ### end Alembic commands ###
