"""Añadir lista_precio_id a Tercero

Revision ID: b06ab1195ff2
Revises: d1f651b78451
Create Date: 2025-10-22 13:25:42.376784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06ab1195ff2'
down_revision: Union[str, Sequence[str], None] = 'd1f651b78451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terceros', sa.Column('lista_precio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'terceros', 'listas_precio', ['lista_precio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_column('terceros', 'lista_precio_id')
    # ### end Alembic commands ###
