"""add_cuenta_costo_produccion_grupo

Revision ID: bab916791fb8
Revises: bce308844daa
Create Date: 2025-12-09 19:07:22.288658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab916791fb8'
down_revision: Union[str, Sequence[str], None] = 'bce308844daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_inventario', sa.Column('cuenta_costo_produccion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_costo_produccion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'cuenta_costo_produccion_id')
    # ### end Alembic commands ###
