"""create_production_tables

Revision ID: bce308844daa
Revises: 6807db7c0dee
Create Date: 2025-12-09 19:03:54.173341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce308844daa'
down_revision: Union[str, Sequence[str], None] = '6807db7c0dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('cantidad_base', sa.Float(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_id'), 'recetas', ['id'], unique=False)
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=True),
    sa.Column('bodega_destino_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_planeada', sa.Float(), nullable=False),
    sa.Column('cantidad_real', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('costo_total_mp', sa.Float(), nullable=True),
    sa.Column('costo_total_mod', sa.Float(), nullable=True),
    sa.Column('costo_total_cif', sa.Float(), nullable=True),
    sa.Column('costo_unitario_final', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bodega_destino_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_produccion_id'), 'ordenes_produccion', ['id'], unique=False)
    op.create_table('receta_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receta_detalles_id'), 'receta_detalles', ['id'], unique=False)
    op.create_table('orden_produccion_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=False),
    sa.Column('bodega_origen_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario_historico', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.Column('fecha_despacho', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['bodega_origen_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_produccion_insumos_id'), 'orden_produccion_insumos', ['id'], unique=False)
    op.create_table('orden_produccion_recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orden_produccion_recursos_id'), 'orden_produccion_recursos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orden_produccion_recursos_id'), table_name='orden_produccion_recursos')
    op.drop_table('orden_produccion_recursos')
    op.drop_index(op.f('ix_orden_produccion_insumos_id'), table_name='orden_produccion_insumos')
    op.drop_table('orden_produccion_insumos')
    op.drop_index(op.f('ix_receta_detalles_id'), table_name='receta_detalles')
    op.drop_table('receta_detalles')
    op.drop_index(op.f('ix_ordenes_produccion_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_index(op.f('ix_recetas_id'), table_name='recetas')
    op.drop_table('recetas')
    # ### end Alembic commands ###
