"""resync_schema_full

Revision ID: bce4561eaa4a
Revises: da94fbacabbd
Create Date: 2025-12-05 19:55:17.059021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce4561eaa4a'
down_revision: Union[str, Sequence[str], None] = 'da94fbacabbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('direccion', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('telefono', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('email', sa.String(), nullable=True))
    op.add_column('empresas', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('grupos_inventario', sa.Column('cuenta_ajuste_faltante_id', sa.Integer(), nullable=True))
    op.add_column('grupos_inventario', sa.Column('cuenta_ajuste_sobrante_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_ajuste_faltante_id'], ['id'])
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_ajuste_sobrante_id'], ['id'])
    op.add_column('plan_cuentas', sa.Column('clase', sa.Integer(), nullable=True))
    op.drop_column('plan_cuentas', 'clase_cuenta')
    op.add_column('productos', sa.Column('stock_minimo', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('stock_maximo', sa.Float(), nullable=True))
    op.add_column('productos', sa.Column('precio_base_manual', sa.Float(), nullable=True))
    op.drop_column('productos', 'precio_venta')
    op.add_column('stock_bodegas', sa.Column('stock_comprometido', sa.Float(), server_default='0', nullable=False))
    op.add_column('terceros', sa.Column('lista_precio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'terceros', 'listas_precio', ['lista_precio_id'], ['id'])
    op.add_column('tipos_documento', sa.Column('es_venta', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tipos_documento', sa.Column('es_compra', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_documento', 'es_compra')
    op.drop_column('tipos_documento', 'es_venta')
    op.drop_constraint(None, 'terceros', type_='foreignkey')
    op.drop_column('terceros', 'lista_precio_id')
    op.drop_column('stock_bodegas', 'stock_comprometido')
    op.add_column('productos', sa.Column('precio_venta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('productos', 'precio_base_manual')
    op.drop_column('productos', 'stock_maximo')
    op.drop_column('productos', 'stock_minimo')
    op.add_column('plan_cuentas', sa.Column('clase_cuenta', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('plan_cuentas', 'clase')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'cuenta_ajuste_sobrante_id')
    op.drop_column('grupos_inventario', 'cuenta_ajuste_faltante_id')
    op.drop_column('empresas', 'logo_url')
    op.drop_column('empresas', 'email')
    op.drop_column('empresas', 'telefono')
    op.drop_column('empresas', 'direccion')
    # ### end Alembic commands ###
