"""add_modo_operacion_to_empresa

Revision ID: c43cc47f91dc
Revises: 96dcf40423b2
Create Date: 2026-01-09 23:46:22.459482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43cc47f91dc'
down_revision: Union[str, Sequence[str], None] = '96dcf40423b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_sistema_clave'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.add_column('empresas', sa.Column('modo_operacion', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'modo_operacion')
    op.create_table('configuracion_sistema',
    sa.Column('clave', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('configuracion_sistema_pkey'))
    )
    op.create_index(op.f('ix_configuracion_sistema_clave'), 'configuracion_sistema', ['clave'], unique=False)
    # ### end Alembic commands ###
