"""Creacion inicial de toda la base de datos

Revision ID: c88a8d8073dd
Revises: 
Create Date: 2025-10-16 16:00:54.622680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88a8d8073dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_inventario', sa.Column('cuenta_ajuste_faltante_id', sa.Integer(), nullable=True))
    op.add_column('grupos_inventario', sa.Column('cuenta_ajuste_sobrante_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_ajuste_sobrante_id'], ['id'])
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_ajuste_faltante_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'cuenta_ajuste_sobrante_id')
    op.drop_column('grupos_inventario', 'cuenta_ajuste_faltante_id')
    # ### end Alembic commands ###
