"""Implementar nueva arquitectura caracteristicas y precios por grupo

Revision ID: d1f651b78451
Revises: 81e008735b1f
Create Date: 2025-10-21 19:10:57.838618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1f651b78451'
down_revision: Union[str, Sequence[str], None] = '81e008735b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_precios_producto_id'), table_name='precios_producto')
    op.drop_table('precios_producto')
    op.drop_constraint(op.f('grupos_inventario_impuesto_predeterminado_id_fkey'), 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'impuesto_predeterminado_id')
    op.add_column('productos', sa.Column('precio_base_manual', sa.Float(), nullable=True))
    op.drop_column('productos', 'caracteristicas')
    op.drop_column('productos', 'precio_venta')
    op.drop_column('productos', 'unidad_medida')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('unidad_medida', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('productos', sa.Column('precio_venta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('productos', sa.Column('caracteristicas', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('productos', 'precio_base_manual')
    op.add_column('grupos_inventario', sa.Column('impuesto_predeterminado_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('grupos_inventario_impuesto_predeterminado_id_fkey'), 'grupos_inventario', 'tasas_impuesto', ['impuesto_predeterminado_id'], ['id'])
    op.create_table('precios_producto',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lista_precio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('producto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lista_precio_id'], ['listas_precio.id'], name=op.f('precios_producto_lista_precio_id_fkey')),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name=op.f('precios_producto_producto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('precios_producto_pkey')),
    sa.UniqueConstraint('lista_precio_id', 'producto_id', name=op.f('uq_precios_producto_lista_producto'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_precios_producto_id'), 'precios_producto', ['id'], unique=False)
    # ### end Alembic commands ###
