"""Añadir es_venta y es_compra a tipos_documento

Revision ID: da94fbacabbd
Revises: 56374b41b01a
Create Date: 2025-11-10 21:29:01.204407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da94fbacabbd'
down_revision: Union[str, Sequence[str], None] = '56374b41b01a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_diagnostics_id'), table_name='rule_diagnostics')
    op.drop_table('rule_diagnostics')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_indicator_key'), table_name='indicators')
    op.drop_table('indicators')
    op.add_column('tipos_documento', sa.Column('es_venta', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tipos_documento', sa.Column('es_compra', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_documento', 'es_compra')
    op.drop_column('tipos_documento', 'es_venta')
    op.create_table('indicators',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indicator_key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('formula', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('units', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('indicators_empresa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('indicators_pkey'))
    )
    op.create_index(op.f('ix_indicators_indicator_key'), 'indicators', ['indicator_key'], unique=True)
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_table('rule_diagnostics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('condition_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('message_template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('rule_diagnostics_empresa_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rule_diagnostics_pkey'))
    )
    op.create_index(op.f('ix_rule_diagnostics_id'), 'rule_diagnostics', ['id'], unique=False)
    # ### end Alembic commands ###
