"""add_cuenta_caja_to_ph_conceptos

Revision ID: db2267ce7084
Revises: 3db1ab3fe27b
Create Date: 2025-12-17 19:42:38.016747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db2267ce7084'
down_revision: Union[str, Sequence[str], None] = '3db1ab3fe27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('empresas', 'prefijo_cxc',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('empresas', 'prefijo_cxp',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'2'::character varying"))
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.drop_constraint(op.f('formatos_documento_impresion_empresa_nombre_key'), 'formatos_documento_impresion', type_='unique')
    op.create_unique_constraint(None, 'formatos_documento_impresion', ['nombre'])
    op.add_column('ph_conceptos', sa.Column('cuenta_caja_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ph_conceptos', 'plan_cuentas', ['cuenta_caja_id'], ['id'])
    op.alter_column('stock_bodegas', 'stock_comprometido',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_bodegas', 'stock_comprometido',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'ph_conceptos', type_='foreignkey')
    op.drop_column('ph_conceptos', 'cuenta_caja_id')
    op.drop_constraint(None, 'formatos_documento_impresion', type_='unique')
    op.create_unique_constraint(op.f('formatos_documento_impresion_empresa_nombre_key'), 'formatos_documento_impresion', ['empresa_id', 'nombre'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.alter_column('empresas', 'prefijo_cxp',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'2'::character varying"))
    op.alter_column('empresas', 'prefijo_cxc',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('empresas', 'logo_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
