"""add_produccion_lifecycle_and_config

Revision ID: e345ba35af63
Revises: 51c27b29d356
Create Date: 2025-12-10 11:01:21.315939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e345ba35af63'
down_revision: Union[str, Sequence[str], None] = '51c27b29d356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('produccion_configuracion',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('empresa_id', sa.Integer(), nullable=False),
    # sa.Column('tipo_documento_orden_id', sa.Integer(), nullable=True),
    # sa.Column('tipo_documento_anulacion_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    # sa.ForeignKeyConstraint(['tipo_documento_orden_id'], ['tipos_documento.id'], ),
    # sa.ForeignKeyConstraint(['tipo_documento_anulacion_id'], ['tipos_documento.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('empresa_id')
    # )
    # op.create_index(op.f('ix_produccion_configuracion_id'), 'produccion_configuracion', ['id'], unique=False)
    
    op.add_column('ordenes_produccion', sa.Column('archivada', sa.Boolean(), nullable=True))
    op.add_column('ordenes_produccion', sa.Column('motivo_anulacion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_produccion', 'motivo_anulacion')
    op.drop_column('ordenes_produccion', 'archivada')
    op.drop_index(op.f('ix_produccion_configuracion_id'), table_name='produccion_configuracion')
    op.drop_table('produccion_configuracion')
    # ### end Alembic commands ###
