"""add_multitenancy_structure

Revision ID: e51ec728bb0b
Revises: 0a7697dcc5a6
Create Date: 2026-01-24 12:13:52.092214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51ec728bb0b'
down_revision: Union[str, Sequence[str], None] = '0a7697dcc5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('padre_id', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('limite_registros_mensual', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('is_template', sa.Boolean(), nullable=True))
    op.add_column('empresas', sa.Column('template_category', sa.String(length=50), nullable=True))
    op.add_column('empresas', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'empresas', 'usuarios', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'empresas', 'empresas', ['padre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_constraint(None, 'empresas', type_='foreignkey')
    op.drop_column('empresas', 'owner_id')
    op.drop_column('empresas', 'template_category')
    op.drop_column('empresas', 'is_template')
    op.drop_column('empresas', 'limite_registros_mensual')
    op.drop_column('empresas', 'padre_id')
    # ### end Alembic commands ###
