"""Sync missing columns for production

Revision ID: ec7e749d3287
Revises: e345ba35af63
Create Date: 2025-12-10 14:42:37.422229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7e749d3287'
down_revision: Union[str, Sequence[str], None] = 'e345ba35af63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grupos_inventario', sa.Column('cuenta_costo_produccion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_costo_produccion_id'], ['id'])
    op.add_column('nomina_configuracion', sa.Column('tipo_nomina_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('nomina_configuracion_empresa_id_key'), 'nomina_configuracion', type_='unique')
    op.create_unique_constraint('uq_config_empresa_tipo', 'nomina_configuracion', ['empresa_id', 'tipo_nomina_id'])
    op.create_foreign_key(None, 'nomina_configuracion', 'nomina_tipos', ['tipo_nomina_id'], ['id'])
    op.add_column('nomina_empleados', sa.Column('tipo_nomina_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'nomina_empleados', 'nomina_tipos', ['tipo_nomina_id'], ['id'])
    op.add_column('ordenes_produccion', sa.Column('archivada', sa.Boolean(), nullable=True))
    op.add_column('ordenes_produccion', sa.Column('motivo_anulacion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_produccion', 'motivo_anulacion')
    op.drop_column('ordenes_produccion', 'archivada')
    op.drop_constraint(None, 'nomina_empleados', type_='foreignkey')
    op.drop_column('nomina_empleados', 'tipo_nomina_id')
    op.drop_constraint(None, 'nomina_configuracion', type_='foreignkey')
    op.drop_constraint('uq_config_empresa_tipo', 'nomina_configuracion', type_='unique')
    op.create_unique_constraint(op.f('nomina_configuracion_empresa_id_key'), 'nomina_configuracion', ['empresa_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('nomina_configuracion', 'tipo_nomina_id')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'cuenta_costo_produccion_id')
    # ### end Alembic commands ###
