"""Sync missing columns for production

Revision ID: ec7e749d3287
Revises: e345ba35af63
Create Date: 2025-12-10 14:42:37.422229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec7e749d3287'
down_revision: Union[str, Sequence[str], None] = 'e345ba35af63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name, column_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    columns = [c['name'] for c in insp.get_columns(table_name)]
    return column_name in columns

def constraint_exists(table_name, constraint_name):
    bind = op.get_bind()
    insp = sa.inspect(bind)
    constraints = [c['name'] for c in insp.get_unique_constraints(table_name)]
    return constraint_name in constraints

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. grupos_inventario.cuenta_costo_produccion_id
    if not column_exists('grupos_inventario', 'cuenta_costo_produccion_id'):
        op.add_column('grupos_inventario', sa.Column('cuenta_costo_produccion_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'grupos_inventario', 'plan_cuentas', ['cuenta_costo_produccion_id'], ['id'])

    # 2. nomina_configuracion.tipo_nomina_id
    if not column_exists('nomina_configuracion', 'tipo_nomina_id'):
        op.add_column('nomina_configuracion', sa.Column('tipo_nomina_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'nomina_configuracion', 'nomina_tipos', ['tipo_nomina_id'], ['id'])

    # 3. Handle constraint replacement safely
    # We want 'uq_config_empresa_tipo' and NO 'nomina_configuracion_empresa_id_key'
    # Check if we need to drop the old one
    if constraint_exists('nomina_configuracion', 'nomina_configuracion_empresa_id_key'):
        op.drop_constraint(op.f('nomina_configuracion_empresa_id_key'), 'nomina_configuracion', type_='unique')
    
    if not constraint_exists('nomina_configuracion', 'uq_config_empresa_tipo'):
        op.create_unique_constraint('uq_config_empresa_tipo', 'nomina_configuracion', ['empresa_id', 'tipo_nomina_id'])

    # 4. nomina_empleados.tipo_nomina_id
    if not column_exists('nomina_empleados', 'tipo_nomina_id'):
        op.add_column('nomina_empleados', sa.Column('tipo_nomina_id', sa.Integer(), nullable=True))
        op.create_foreign_key(None, 'nomina_empleados', 'nomina_tipos', ['tipo_nomina_id'], ['id'])

    # 5. ordenes_produccion.archivada
    if not column_exists('ordenes_produccion', 'archivada'):
        op.add_column('ordenes_produccion', sa.Column('archivada', sa.Boolean(), nullable=True))

    # 6. ordenes_produccion.motivo_anulacion
    if not column_exists('ordenes_produccion', 'motivo_anulacion'):
        op.add_column('ordenes_produccion', sa.Column('motivo_anulacion', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We won't add complex logic here, manual downgrade might be needed if state is messy
    op.drop_column('ordenes_produccion', 'motivo_anulacion')
    op.drop_column('ordenes_produccion', 'archivada')
    op.drop_constraint(None, 'nomina_empleados', type_='foreignkey')
    op.drop_column('nomina_empleados', 'tipo_nomina_id')
    op.drop_constraint(None, 'nomina_configuracion', type_='foreignkey')
    op.drop_constraint('uq_config_empresa_tipo', 'nomina_configuracion', type_='unique')
    op.create_unique_constraint(op.f('nomina_configuracion_empresa_id_key'), 'nomina_configuracion', ['empresa_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('nomina_configuracion', 'tipo_nomina_id')
    op.drop_constraint(None, 'grupos_inventario', type_='foreignkey')
    op.drop_column('grupos_inventario', 'cuenta_costo_produccion_id')
    # ### end Alembic commands ###
