"""Add tasa_usura and fecha_sincronizacion to indicadores_economicos

Revision ID: ee1ef08d68c0
Revises: c94a1add49e9
Create Date: 2026-02-21 20:00:59.192177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1ef08d68c0'
down_revision: Union[str, Sequence[str], None] = 'c94a1add49e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_sistema_clave'), table_name='configuracion_sistema')
    op.drop_table('configuracion_sistema')
    op.drop_constraint(op.f('uq_plan_empresa_periodo'), 'control_plan_mensual', type_='unique')
    op.create_index('uq_plan_empresa_periodo', 'control_plan_mensual', ['empresa_id', 'anio', 'mes'], unique=True)
    op.create_index(op.f('ix_control_plan_mensual_id'), 'control_plan_mensual', ['id'], unique=False)
    op.alter_column('empresas', 'dv',
               existing_type=sa.VARCHAR(length=1),
               comment='Dígito de Verificación',
               existing_nullable=True)
    op.alter_column('empresas', 'tipo_documento',
               existing_type=sa.VARCHAR(length=5),
               comment='31=NIT, 13=Cedula',
               existing_nullable=True,
               existing_server_default=sa.text("'31'::character varying"))
    op.alter_column('empresas', 'tipo_persona',
               existing_type=sa.VARCHAR(length=1),
               comment='1=Juridica, 2=Natural',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
    op.alter_column('empresas', 'regimen_fiscal',
               existing_type=sa.VARCHAR(length=5),
               comment='48=IVA, 49=No IVA',
               existing_nullable=True,
               existing_server_default=sa.text("'48'::character varying"))
    op.alter_column('empresas', 'responsabilidad_fiscal',
               existing_type=sa.VARCHAR(length=20),
               comment='Codigo Resp. Fiscal',
               existing_nullable=True,
               existing_server_default=sa.text("'R-99-PN'::character varying"))
    op.alter_column('empresas', 'municipio_dane',
               existing_type=sa.VARCHAR(length=10),
               comment='Codigo DANE Municipio',
               existing_nullable=True)
    op.alter_column('empresas', 'is_lite_mode',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('empresas', 'saldo_facturas_venta',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'saldo_documentos_soporte',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_mov_inv_bodega'), table_name='movimientos_inventario')
    op.drop_index(op.f('idx_mov_inv_documento'), table_name='movimientos_inventario')
    op.drop_index(op.f('idx_mov_inv_fecha'), table_name='movimientos_inventario')
    op.drop_index(op.f('idx_mov_inv_producto'), table_name='movimientos_inventario')
    op.alter_column('productos', 'controlar_inventario',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('terceros', 'responsabilidad_fiscal',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('terceros', 'tipo_documento',
               existing_type=sa.VARCHAR(length=5),
               comment='13=Cedula, 31=NIT',
               existing_nullable=True,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('terceros', 'tipo_persona',
               existing_type=sa.VARCHAR(length=1),
               comment='1=Juridica, 2=Natural',
               existing_nullable=True,
               existing_server_default=sa.text("'2'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terceros', 'tipo_persona',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='1=Juridica, 2=Natural',
               existing_nullable=True,
               existing_server_default=sa.text("'2'::character varying"))
    op.alter_column('terceros', 'tipo_documento',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='13=Cedula, 31=NIT',
               existing_nullable=True,
               existing_server_default=sa.text("'13'::character varying"))
    op.alter_column('terceros', 'responsabilidad_fiscal',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('productos', 'controlar_inventario',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('idx_mov_inv_producto'), 'movimientos_inventario', ['producto_id'], unique=False)
    op.create_index(op.f('idx_mov_inv_fecha'), 'movimientos_inventario', ['fecha'], unique=False)
    op.create_index(op.f('idx_mov_inv_documento'), 'movimientos_inventario', ['documento_id'], unique=False)
    op.create_index(op.f('idx_mov_inv_bodega'), 'movimientos_inventario', ['bodega_id'], unique=False)
    op.alter_column('empresas', 'saldo_documentos_soporte',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'saldo_facturas_venta',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('empresas', 'is_lite_mode',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('empresas', 'municipio_dane',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Codigo DANE Municipio',
               existing_nullable=True)
    op.alter_column('empresas', 'responsabilidad_fiscal',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Codigo Resp. Fiscal',
               existing_nullable=True,
               existing_server_default=sa.text("'R-99-PN'::character varying"))
    op.alter_column('empresas', 'regimen_fiscal',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='48=IVA, 49=No IVA',
               existing_nullable=True,
               existing_server_default=sa.text("'48'::character varying"))
    op.alter_column('empresas', 'tipo_persona',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='1=Juridica, 2=Natural',
               existing_nullable=True,
               existing_server_default=sa.text("'1'::character varying"))
    op.alter_column('empresas', 'tipo_documento',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='31=NIT, 13=Cedula',
               existing_nullable=True,
               existing_server_default=sa.text("'31'::character varying"))
    op.alter_column('empresas', 'dv',
               existing_type=sa.VARCHAR(length=1),
               comment=None,
               existing_comment='Dígito de Verificación',
               existing_nullable=True)
    op.drop_index(op.f('ix_control_plan_mensual_id'), table_name='control_plan_mensual')
    op.drop_index('uq_plan_empresa_periodo', table_name='control_plan_mensual')
    op.create_unique_constraint(op.f('uq_plan_empresa_periodo'), 'control_plan_mensual', ['empresa_id', 'anio', 'mes'], postgresql_nulls_not_distinct=False)
    op.create_table('configuracion_sistema',
    sa.Column('clave', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('valor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('clave', name=op.f('configuracion_sistema_pkey'))
    )
    op.create_index(op.f('ix_configuracion_sistema_clave'), 'configuracion_sistema', ['clave'], unique=False)
    # ### end Alembic commands ###
