"""create consumo tables v4

Revision ID: f1cd9d19816d
Revises: 4b6ed1a29389
Create Date: 2026-01-07 21:31:06.888591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cd9d19816d'
down_revision: Union[str, Sequence[str], None] = '4b6ed1a29389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_roles_empresa'), table_name='roles', postgresql_where='(empresa_id IS NOT NULL)')
    op.drop_index(op.f('uq_roles_global'), table_name='roles', postgresql_where='(empresa_id IS NULL)')
    op.drop_constraint(op.f('roles_empresa_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_empresa_id_fkey'), 'roles', 'empresas', ['empresa_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('uq_roles_global'), 'roles', ['nombre'], unique=True, postgresql_where='(empresa_id IS NULL)')
    op.create_index(op.f('uq_roles_empresa'), 'roles', ['nombre', 'empresa_id'], unique=True, postgresql_where='(empresa_id IS NOT NULL)')
    # ### end Alembic commands ###
