"""add_ph_tipo_doc_factura

Revision ID: f596acd9b6b3
Revises: 68c2ce2bbc2b
Create Date: 2025-12-08 00:00:34.634798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f596acd9b6b3'
down_revision: Union[str, Sequence[str], None] = '68c2ce2bbc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ph_configuracion', sa.Column('tipo_documento_factura_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ph_configuracion', 'tipos_documento', ['tipo_documento_factura_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ph_configuracion', type_='foreignkey')
    op.drop_column('ph_configuracion', 'tipo_documento_factura_id')
    # ### end Alembic commands ###
