"""Creacion inicial de base de datos para nuevo PC

Revision ID: 86597980417b
Revises: 
Create Date: 2025-10-12 20:14:31.838094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86597980417b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_inicio_operaciones', sa.Date(), nullable=True),
    sa.Column('limite_registros', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permisos_id'), 'permisos', ['id'], unique=False)
    op.create_index(op.f('ix_permisos_nombre'), 'permisos', ['nombre'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_nombre'), 'roles', ['nombre'], unique=True)
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_bodegas_empresa_nombre')
    )
    op.create_index(op.f('ix_bodegas_id'), 'bodegas', ['id'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('centros_costo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('permite_movimiento', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_padre_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_padre_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_centros_costo_empresa_codigo')
    )
    op.create_index(op.f('ix_centros_costo_codigo'), 'centros_costo', ['codigo'], unique=False)
    op.create_index(op.f('ix_centros_costo_id'), 'centros_costo', ['id'], unique=False)
    op.create_table('periodos_cerrados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('cerrado_por_usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cerrado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'ano', 'mes', name='_empresa_ano_mes_uc')
    )
    op.create_index(op.f('ix_periodos_cerrados_id'), 'periodos_cerrados', ['id'], unique=False)
    op.create_table('plan_cuentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('permite_movimiento', sa.Boolean(), nullable=True),
    sa.Column('funcion_especial', sa.String(length=50), nullable=True),
    sa.Column('clase_cuenta', sa.String(length=50), nullable=True),
    sa.Column('es_cuenta_de_ingresos', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('cuenta_padre_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_padre_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_plan_cuentas_empresa_codigo')
    )
    op.create_index(op.f('ix_plan_cuentas_es_cuenta_de_ingresos'), 'plan_cuentas', ['es_cuenta_de_ingresos'], unique=False)
    op.create_index(op.f('ix_plan_cuentas_id'), 'plan_cuentas', ['id'], unique=False)
    op.create_index(op.f('ix_plan_cuentas_nombre'), 'plan_cuentas', ['nombre'], unique=False)
    op.create_table('terceros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=False),
    sa.Column('dv', sa.String(length=1), nullable=True),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=True),
    sa.Column('es_cliente', sa.Boolean(), nullable=True),
    sa.Column('es_proveedor', sa.Boolean(), nullable=True),
    sa.Column('es_empleado', sa.Boolean(), nullable=False),
    sa.Column('responsabilidad_fiscal', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('actividad_economica_ciiu', sa.String(length=10), nullable=True),
    sa.Column('es_regimen_simple', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nit', name='uq_tercero_empresa_nit')
    )
    op.create_index(op.f('ix_terceros_empresa_id'), 'terceros', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_terceros_id'), 'terceros', ['id'], unique=False)
    op.create_index(op.f('ix_terceros_nit'), 'terceros', ['nit'], unique=False)
    op.create_index(op.f('ix_terceros_razon_social'), 'terceros', ['razon_social'], unique=False)
    op.create_table('usuario_permisos_excepciones',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.Column('permitido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'permiso_id')
    )
    op.create_table('usuario_roles',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'rol_id')
    )
    op.create_table('conceptos_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'descripcion', name='uq_conceptos_favoritos_empresa_descripcion')
    )
    op.create_index(op.f('ix_conceptos_favoritos_id'), 'conceptos_favoritos', ['id'], unique=False)
    op.create_table('grupos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cuenta_inventario_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_ingreso_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_costo_venta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_costo_venta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_ingreso_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_inventario_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_grupos_inventario_empresa_nombre')
    )
    op.create_index(op.f('ix_grupos_inventario_id'), 'grupos_inventario', ['id'], unique=False)
    op.create_table('tasas_impuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tasa', sa.Float(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_iva_descontable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_iva_descontable_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_tasas_impuesto_empresa_nombre')
    )
    op.create_index(op.f('ix_tasas_impuesto_id'), 'tasas_impuesto', ['id'], unique=False)
    op.create_table('tipos_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.Column('numeracion_manual', sa.Boolean(), nullable=False),
    sa.Column('funcion_especial', sa.String(length=50), nullable=True),
    sa.Column('afecta_inventario', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('cuenta_caja_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_debito_cxc_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_credito_cxc_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_debito_cxp_id', sa.Integer(), nullable=True),
    sa.Column('cuenta_credito_cxp_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cuenta_caja_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_credito_cxc_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_credito_cxp_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_debito_cxc_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['cuenta_debito_cxp_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_tipos_documento_empresa_codigo')
    )
    op.create_index(op.f('ix_tipos_documento_id'), 'tipos_documento', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('beneficiario_id', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_operacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('formatos_documento_impresion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=True),
    sa.Column('contenido_html', sa.Text(), nullable=False),
    sa.Column('variables_ejemplo_json', sa.JSON(), nullable=True),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultima_modificacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_formatos_documento_impresion_id'), 'formatos_documento_impresion', ['id'], unique=False)
    op.create_table('plantillas_maestras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre_plantilla', sa.String(length=255), nullable=False),
    sa.Column('tipo_documento_id_sugerido', sa.Integer(), nullable=True),
    sa.Column('beneficiario_id_sugerido', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id_sugerido', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id_sugerido'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['centro_costo_id_sugerido'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id_sugerido'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nombre_plantilla', name='uq_plantillas_maestras_empresa_nombre')
    )
    op.create_index(op.f('ix_plantillas_maestras_id'), 'plantillas_maestras', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('impuesto_iva_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('es_servicio', sa.Boolean(), nullable=False),
    sa.Column('metodo_costeo', sa.String(length=50), nullable=False),
    sa.Column('costo_promedio', sa.Float(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_inventario.id'], ),
    sa.ForeignKeyConstraint(['impuesto_iva_id'], ['tasas_impuesto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_productos_empresa_codigo')
    )
    op.create_index(op.f('ix_productos_codigo'), 'productos', ['codigo'], unique=False)
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_nombre'), 'productos', ['nombre'], unique=False)
    op.create_table('aplicacion_pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_factura_id', sa.Integer(), nullable=False),
    sa.Column('documento_pago_id', sa.Integer(), nullable=False),
    sa.Column('valor_aplicado', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fecha_aplicacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_factura_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['documento_pago_id'], ['documentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_operaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('documento_id_asociado', sa.Integer(), nullable=True),
    sa.Column('email_usuario', sa.String(length=255), nullable=True),
    sa.Column('fecha_operacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('tipo_operacion', sa.String(length=50), nullable=False),
    sa.Column('razon', sa.String(length=500), nullable=True),
    sa.Column('detalle_documento_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id_asociado'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_operaciones_documento_id_asociado'), 'log_operaciones', ['documento_id_asociado'], unique=False)
    op.create_index(op.f('ix_log_operaciones_id'), 'log_operaciones', ['id'], unique=False)
    op.create_table('movimientos_contables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_contables_id'), 'movimientos_contables', ['id'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('costo_unitario', sa.Float(), nullable=False),
    sa.Column('costo_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_inventario_id'), 'movimientos_inventario', ['id'], unique=False)
    op.create_table('plantillas_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantilla_maestra_id', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plantilla_maestra_id'], ['plantillas_maestras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantillas_detalles_id'), 'plantillas_detalles', ['id'], unique=False)
    op.create_table('stock_bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'bodega_id', name='uq_stock_bodegas_producto_bodega')
    )
    op.create_index(op.f('ix_stock_bodegas_id'), 'stock_bodegas', ['id'], unique=False)
    op.create_table('documentos_eliminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_original', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('beneficiario_id', sa.Integer(), nullable=True),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('usuario_creador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_eliminacion', sa.DateTime(), nullable=True),
    sa.Column('usuario_eliminacion_id', sa.Integer(), nullable=True),
    sa.Column('log_eliminacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiario_id'], ['terceros.id'], ),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['log_eliminacion_id'], ['log_operaciones.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento_id'], ['tipos_documento.id'], ),
    sa.ForeignKeyConstraint(['usuario_creador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_eliminacion_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_eliminados_id'), 'documentos_eliminados', ['id'], unique=False)
    op.create_table('movimientos_eliminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_original', sa.Integer(), nullable=False),
    sa.Column('documento_eliminado_id', sa.Integer(), nullable=False),
    sa.Column('documento_id_original', sa.Integer(), nullable=False),
    sa.Column('cuenta_id', sa.Integer(), nullable=False),
    sa.Column('centro_costo_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.Text(), nullable=True),
    sa.Column('debito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('credito', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['centro_costo_id'], ['centros_costo.id'], ),
    sa.ForeignKeyConstraint(['cuenta_id'], ['plan_cuentas.id'], ),
    sa.ForeignKeyConstraint(['documento_eliminado_id'], ['documentos_eliminados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_eliminados_id'), 'movimientos_eliminados', ['id'], unique=False)
    op.create_index(op.f('ix_movimientos_eliminados_id_original'), 'movimientos_eliminados', ['id_original'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_eliminados_id_original'), table_name='movimientos_eliminados')
    op.drop_index(op.f('ix_movimientos_eliminados_id'), table_name='movimientos_eliminados')
    op.drop_table('movimientos_eliminados')
    op.drop_index(op.f('ix_documentos_eliminados_id'), table_name='documentos_eliminados')
    op.drop_table('documentos_eliminados')
    op.drop_index(op.f('ix_stock_bodegas_id'), table_name='stock_bodegas')
    op.drop_table('stock_bodegas')
    op.drop_index(op.f('ix_plantillas_detalles_id'), table_name='plantillas_detalles')
    op.drop_table('plantillas_detalles')
    op.drop_index(op.f('ix_movimientos_inventario_id'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_contables_id'), table_name='movimientos_contables')
    op.drop_table('movimientos_contables')
    op.drop_index(op.f('ix_log_operaciones_id'), table_name='log_operaciones')
    op.drop_index(op.f('ix_log_operaciones_documento_id_asociado'), table_name='log_operaciones')
    op.drop_table('log_operaciones')
    op.drop_table('aplicacion_pagos')
    op.drop_index(op.f('ix_productos_nombre'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_index(op.f('ix_productos_codigo'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_plantillas_maestras_id'), table_name='plantillas_maestras')
    op.drop_table('plantillas_maestras')
    op.drop_index(op.f('ix_formatos_documento_impresion_id'), table_name='formatos_documento_impresion')
    op.drop_table('formatos_documento_impresion')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_tipos_documento_id'), table_name='tipos_documento')
    op.drop_table('tipos_documento')
    op.drop_index(op.f('ix_tasas_impuesto_id'), table_name='tasas_impuesto')
    op.drop_table('tasas_impuesto')
    op.drop_index(op.f('ix_grupos_inventario_id'), table_name='grupos_inventario')
    op.drop_table('grupos_inventario')
    op.drop_index(op.f('ix_conceptos_favoritos_id'), table_name='conceptos_favoritos')
    op.drop_table('conceptos_favoritos')
    op.drop_table('usuario_roles')
    op.drop_table('usuario_permisos_excepciones')
    op.drop_index(op.f('ix_terceros_razon_social'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_nit'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_id'), table_name='terceros')
    op.drop_index(op.f('ix_terceros_empresa_id'), table_name='terceros')
    op.drop_table('terceros')
    op.drop_index(op.f('ix_plan_cuentas_nombre'), table_name='plan_cuentas')
    op.drop_index(op.f('ix_plan_cuentas_id'), table_name='plan_cuentas')
    op.drop_index(op.f('ix_plan_cuentas_es_cuenta_de_ingresos'), table_name='plan_cuentas')
    op.drop_table('plan_cuentas')
    op.drop_index(op.f('ix_periodos_cerrados_id'), table_name='periodos_cerrados')
    op.drop_table('periodos_cerrados')
    op.drop_index(op.f('ix_centros_costo_id'), table_name='centros_costo')
    op.drop_index(op.f('ix_centros_costo_codigo'), table_name='centros_costo')
    op.drop_table('centros_costo')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_bodegas_id'), table_name='bodegas')
    op.drop_table('bodegas')
    op.drop_index(op.f('ix_roles_nombre'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permisos_nombre'), table_name='permisos')
    op.drop_index(op.f('ix_permisos_id'), table_name='permisos')
    op.drop_table('permisos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
